name: lint and tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.10']

    steps:
    - uses: actions/checkout@v2
    - name: setup python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: install deps
      run: |
        python -m pip install --upgrade pip setuptools wheel flake8 twine
        python setup.py develop
    - name: lint
      run: |
        python -m flake8
    - name: tests
      run: |
        python setup.py test
    # Test the build and run twine to check we are pypi compatible
    - name: check build
      run: |
        python setup.py bdist && twine check dist/*
    # Even thought we have readthedocs build docs on every MR, this is useful
    # because we build with -W --keep-going (see Makefile) and this will
    # therefore fail on warnings that could be ignored by readthedocs and
    # lead to half-broken docs
    - name: build docs
      run: |
        cd docs
        python -m pip install -r requirements.txt
        make html

